name: Changelog

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    uses: Perform-Partners/github-workflows/.github/workflows/changelog.yml@main
    with:
      event_name: ${{ github.event_name }}
